default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: postgres
  username: postgres
  password: 123123
  timeout: 5000

development:
  <<: *default
  database: backend_development

test:
  <<: *default
  database: backend_test
